name: Deploy Next.js app

on:
  push:
    branches: [main] # или ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.3"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY }}
          MEDUSA_BACKEND_URL: ${{ secrets.MEDUSA_BACKEND_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_DEFAULT_REGION: ${{ secrets.NEXT_PUBLIC_DEFAULT_REGION }}
          REVALIDATE_SECRET: ${{ secrets.REVALIDATE_SECRET }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/projects/aromav2/aroma-storefront
            git pull origin main
            npm install
            npm run build
            pm2 restart aroma
